parameters:
    pusher.app_id: "%env(PUSHER_APP_ID)%"
    pusher.key: "%env(PUSHER_KEY)%"
    pusher.secret: "%env(PUSHER_SECRET)%"
    pusher.cluster: "%env(PUSHER_CLUSTER)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\PusherService:
        arguments:
            $appId: "%env(PUSHER_APP_ID)%"
            $key: "%env(PUSHER_KEY)%"
            $secret: "%env(PUSHER_SECRET)%"
            $cluster: "%env(PUSHER_CLUSTER)%"
